homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
    # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 52
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  internal_url: !secret internal_url
  external_url: !secret external_url

  customize: !include customize.yaml

  # Packages
  packages: !include_dir_named packages/

  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password

discovery:

system_health:

mobile_app:

http:

upnp:
  local_ip: !secret local_ip

frontend:
  themes: !include_dir_merge_named ./themes/
  javascript_version: auto

lovelace_gen:

lovelace:
  mode: yaml
  resources:
    !include lovelace/resources/resources.yaml
  dashboards:
    lovelace-tablet:
      mode: yaml
      filename: ui-tablet.yaml
      title: "Tablet UI"
      icon: mdi:tablet-ipad
      show_in_sidebar: true
    lovelace-tablet-new:
      mode: yaml
      filename: ui-tablet-new.yaml
      title: "Tablet UI New"
      icon: mdi:tablet-ipad
      show_in_sidebar: true
  
hacs:
  token: !secret hacs_token

browser_mod:
  devices:
    c7cfd816-f3800c10:
      name: mbp_chrome
    4381d7ed-95427ac3:
      name: tablet_fkb

# Enables configuration UI
config:

history:

logger:
  default: warning
  logs:
    # log level for HA core
    homeassistant.core: fatal
    
    # log level for MQTT integration
    homeassistant.components.mqtt: warning
    
    # log level for deCONZ
    # homeassistant.components.deconz: debug

    # log level for Alexa Media Player
    # alexapy: debug

recorder:
  db_url: !secret mysql_connection
  auto_purge: true
  purge_keep_days: 30

# influxdb:
#   host: !secret influxdb_host
#   port: !secret influxdb_port
#   database: homeassistant
#   username: !secret influxdb_user
#   password: !secret influxdb_password
#   max_retries: 3
#   default_measurement: state

deconz:
  host: !secret deconz_host
  port: !secret deconz_port

person:

map:

# Track the sun
sun:

panel_iframe:
  nodered:
    title: 'Node-RED'
    icon: 'mdi:chart-timeline'
    url: 'http://192.168.50.20:1880/' 
  phoscon:
    title: 'Phoscon'
    icon: 'mdi:zigbee'
    url: 'http://192.168.50.20:9082/' 

automation: !include_dir_merge_list automation
group: !include_dir_merge_named configuration/groups/ 
# homekit: !include ./configuration/homekit.yaml
# input_boolean: !include ./configuration/input_boolean.yaml
# input_select: !include ./configuration/input_select.yaml
# switch: !include ./configuration/switch.yaml
sensor: !include ./configuration/sensor.yaml
