# Custom Card Resources
# resources:
#   !include lovelace/resources/resources.yaml
 
# Custom Header
# You will need to hide views if you want to
# have views that behave like popup cards!
custom_header:
  !include lovelace/custom_header/custom_header.yaml


# Decluttering Templates
# These are the templates used to avoid too much
# duplicate code.
decluttering_templates:
  !include lovelace/templates/decluttering_templates.yaml # Changed/Added in 0.12.0
     
# Views
# The following 5 views are swipable, the order
# of these 5 files is the swipe order as well.
# The first view is the page 0. In my setup
# the interface defaults to view 1.
title: Home
# background: var(--background-image) # This is the background image that will be used in all the views. (currently backgrounds are set in themes, dont edit this if you want themes to work)
# background: #EEEEEE;
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/heating.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/printer.yaml
  - !include lovelace/views/system.yaml
#  - !include lovelace/views/person1.yaml
  - !include lovelace/views/weather.yaml
 # - !include lovelace/views/car.yaml
#  - !include lovelace/views/he.yaml
  - !include lovelace/views/corona.yaml
  - !include lovelace/views/settings.yaml
