# Custom Card Resources
resources:
  !include lovelace/resources/resources.yaml

# Compact Custom Header
cch:
  !include lovelace/cch/compact-custom-header.yaml

# Decluttering Templates
decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

title: Home
background: var(--background-image)

views:
  - !include lovelace/views/heating.yaml
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/system.yaml


