# Custom Card Resources
resources:
  !include lovelace/resources/resources.yaml

# Compact Custom Header
cch:
  menu: hide
  options: hide
  notifications: hide
  voice: hide
  header: false
  chevrons: false
  notify_indicator_color: "#e80000"
  swipe: true
  swipe_wrap: false
  background: 'rgba(0,0,0,0.3)'
  #hide_tabs: '5 to 30'
  default_tab: 1

# Decluttering Templates
decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

title: Home
background: var(--background-image)

views:
  - !include lovelace/views/heating.yaml
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/system.yaml


