title: Settings
path: settings
cards:
  - type: entities
    style: |
      ha-card {
        border: 0;
        box-shadow: none;
        padding: 10px;
      }
    entities:
      - type: custom:hui-entities-card
        style: |
          ha-card {
            border: 1px solid rgba(255,255,255,0.20);
            border-radius: 12px;
            box-shadow: -6px -6px 26px 0 rgba(255,255,255,0.83), 6px 6px 16px 0 rgba(217,210,200,1);
            margin: 20px 0;
          }
        entities:
          - type: custom:decluttering-card
            template: header_text
            variables:
              - content: '## Nachttische'
          - type: custom:multiple-entity-row
            entity: light.nightstand_mario_light
            name: 'Mario'
            state_header: 'Licht'
            unit: ' '
            entities:
              - entity: binary_sensor.nightstand_mario_motion
                name: 'Bewegung'
              - entity: sensor.nightstand_mario_brightness
                name: 'Helligkeit'
          - type: custom:fold-entity-row
            head:
              type: section
              label: Einstellungen
            entities:
              - input_number.nightstand_mario_brightness_trigger
              - input_number.nightstand_mario_light_duration
              - input_number.nightstand_mario_default_brightness
          - type: custom:light-entity-card
            entity: light.nightstand_mario_settings
            header: false
            persist_features: true

          - type: custom:multiple-entity-row
            entity: light.nightstand_sandra_light
            name: 'Sandra'
            state_header: 'Licht'
            unit: ' '
            entities:
              - entity: binary_sensor.motion_nightstand_sandra
                name: 'Bewegung'
              - entity: sensor.lightlevel_nightstand_sandra
                name: 'Helligkeit'
          - type: custom:fold-entity-row
            head:
              type: section
              label: Einstellungen
            entities:
              - input_number.nightstand_sandra_brightness_trigger
              - input_number.nightstand_sandra_light_duration
              - input_number.nightstand_sandra_default_brightness
          - type: custom:light-entity-card
            entity: light.nightstand_sandra_settings
            header: false
            persist_features: true
