- alias: "Turn kitchen light on"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.remote_kitchen_light
      to: 'on'  
  action:
    service: homeassistant.turn_on
    entity_id: switch.kitchen_plug
  
- alias: "Turn kitchen light off"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.remote_kitchen_light
      to: 'off'  
  action:
    service: homeassistant.turn_off
    entity_id: switch.kitchen_plug

- alias: "Turn TV on"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.remote_television
      to: 'on'  
  action:
    service: homeassistant.turn_on
    entity_id: switch.tv_plug
  
- alias: "Turn TV off"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.remote_television
      to: 'off'  
  action:
    service: homeassistant.turn_off
    entity_id: switch.tv_plug

- alias: "Turn Cube on"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.remote_cube
      to: 'on'  
  action:
    service: homeassistant.turn_on
    entity_id: switch.cube_plug
  
- alias: "Turn Cube off"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.remote_cube
      to: 'off'  
  action:
    service: homeassistant.turn_off
    entity_id: switch.cube_plug

- alias: "Automatic kitchen light"
  hide_entity: true
  initial_state: on
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_kitchen
    to: 'on'
  - platform: state
    entity_id: binary_sensor.motion_kitchen
    to: 'off'
    for:
      minutes: 5
  # condition:
  #   condition: and
  #   conditions:
  #   - condition: state
  #     entity_id: group.all_devices
  #     state: 'home'
  #   - condition: or
  #     conditions:
  #     - condition: and
  #       conditions:
  #       - condition: state
  #         entity_id: binary_sensor.motionsensor_kitchen
  #         state: 'on'
  #       - condition: numeric_state
  #         entity_id: sensor.luxsensor_kitchen
  #         below: 100
  #     - condition: state
  #       entity_id: binary_sensor.motionsensor_kitchen
  #       state: 'off'
  action:
    service_template: >
      switch.turn_{{ trigger.to_state.state}}
    # data_template:
    #   transition: 1
    entity_id: switch.kitchen_plug
