- alias: "Turn kitchen light on"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.kitchen_light
      to: 'on'  
  action:
    service: homeassistant.turn_on
    entity_id: switch.kitchen_plug
  
- alias: "Turn kitchen light off"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.kitchen_light
      to: 'off'  
  action:
    service: homeassistant.turn_off
    entity_id: switch.kitchen_plug

- alias: "Turn TV on"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.television
      to: 'on'  
  action:
    service: homeassistant.turn_on
    entity_id: switch.tv_plug
  
- alias: "Turn TV off"
  hide_entity: true
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.television
      to: 'off'  
  action:
    service: homeassistant.turn_off
    entity_id: switch.tv_plug
