- alias: "Automatic kitchen light"
  hide_entity: true
  initial_state: on
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_kitchen
    to: 'on'
  - platform: state
    entity_id: binary_sensor.motion_kitchen
    to: 'off'
    for:
      minutes: 5
  # condition:
  #   condition: and
  #   conditions:
  #   - condition: state
  #     entity_id: group.all_devices
  #     state: 'home'
  #   - condition: or
  #     conditions:
  #     - condition: and
  #       conditions:
  #       - condition: state
  #         entity_id: binary_sensor.motionsensor_kitchen
  #         state: 'on'
  #       - condition: numeric_state
  #         entity_id: sensor.luxsensor_kitchen
  #         below: 100
  #     - condition: state
  #       entity_id: binary_sensor.motionsensor_kitchen
  #       state: 'off'
  action:
    service_template: >
      switch.turn_{{ trigger.to_state.state}}
    # data_template:
    #   transition: 1
    entity_id: switch.kitchen_plug
