- alias: "Xiaomi Aqara Motion Duration Setup"
  initial_state: on
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: deconz.configure
      data:
        entity: binary_sensor.motion_kitchen
        field: "/config"
        data: {"duration": 5}
    - service: deconz.configure
      data:
        entity: binary_sensor.motion_nightstand_sandra
        field: "/config"
        data: {"duration": 5}
    - service: deconz.configure
      data:
        entity: binary_sensor.motion_nightstand_mario
        field: "/config"
        data: {"duration": 5}
    