# - platform: yr

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: processor_use

- platform: rest
  resource: !secret tankerkoenig_shell
  name: shell_heek_diesel
  unit_of_measurement: '€'
  value_template: !secret tankerkoenig_shell_value
  scan_interval: 900

- platform: rest
  resource: !secret tankerkoenig_esso
  name: esso_ddorf_diesel
  unit_of_measurement: '€'
  value_template: !secret tankerkoenig_esso_value
  scan_interval: 900

# Template All Doors
- platform: template
  sensors:
    current_doors_open:
      friendly_name: All Doors Currently Open
      value_template: >-
        {{ states|selectattr('entity_id','in',state_attr('group.all_door_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}

# Template All Windows
- platform: template
  sensors:
    current_windows_open:
      friendly_name: All Windows Currently Open
      value_template: >-
        {{ states|selectattr('entity_id','in',state_attr('group.all_window_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}

# Template All Sensors
- platform: template
  sensors:
    current_sensors_on:
      friendly_name: All Sensors Currently On
      value_template: >-
        {{ states|selectattr('entity_id','in',state_attr('group.all_motion_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
