google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sensor:
  - platform: template
    next_garbage:
      friendly_name: 'Restmülltonne'
      unit_of_measurement: 'days'
      entity_id: calendar.get_garbage
      value_template: >
        {% set due_date = (as_timestamp(states.calendar.get_garbage.attributes.start_time) | int) %}
        {% set todays_date = (now().strftime("%s") | int ) %}
        {% if todays_date == due_date %}
         {% set countdown = "Heute" %}
        {% else %}
          {% set countdown = ((due_date - todays_date | int) / 24 / 60 / 60) | round(0) %}
        {% endif %}
        {{countdown}}

    next_organic:
      friendly_name: 'Biotonne'
      unit_of_measurement: 'days'
      entity_id: calendar.get_organic
      value_template: >
        {% set due_date = (as_timestamp(states.calendar.get_organic.attributes.start_time) | int) %}
        {% set todays_date = (now().strftime("%s") | int ) %}
        {% if todays_date == due_date %}
         {% set countdown = "Heute" %}
        {% else %}
          {% set countdown = ((due_date - todays_date | int) / 24 / 60 / 60) | round(0) %}
        {% endif %}
        {{countdown}}

    next_recycling:
      friendly_name: 'Gelbe Tonne'
      unit_of_measurement: 'days'
      entity_id: calendar.get_recycling
      value_template: >
        {% set due_date = (as_timestamp(states.calendar.get_recycling.attributes.start_time) | int) %}
        {% set todays_date = (now().strftime("%s") | int ) %}
        {% if todays_date == due_date %}
         {% set countdown = "Heute" %}
        {% else %}
          {% set countdown = ((due_date - todays_date | int) / 24 / 60 / 60) | round(0) %}
        {% endif %}
        {{countdown}}

    next_paper:
      friendly_name: 'Papiertonne'
      unit_of_measurement: 'days'
      entity_id: calendar.get_paper
      value_template: >
        {% set due_date = (as_timestamp(states.calendar.get_paper.attributes.start_time) | int) %}
        {% set todays_date = (now().strftime("%s") | int ) %}
        {% if todays_date == due_date %}
         {% set countdown = "Heute" %}
        {% else %}
          {% set countdown = ((due_date - todays_date | int) / 24 / 60 / 60) | round(0) %}
        {% endif %}
        {{countdown}}
