automation:
  - id: doorbell_rings
    alias: "Doorbell rings"
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.doorbell
      from: 'off'
      to: 'on'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.echo_kuche_vol
        value: "{{ states.media_player.echo_kuche.attributes.volume_level | float }}"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.echo_kuche
        volume_level: "1.0"
    - service: media_player.play_media
      data:
        entity_id: media_player.echo_kuche
        media_content_type: sound
        media_content_id: amzn_sfx_doorbell_01
    # - delay: '00:00:03'
    - service: notify.alexa_media
      data:
        target: 
          - media_player.echo_kuche
        data:
          type: tts
        message: "Es hat geklingelt!"
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.echo_kuche
        volume_level: "{{ states.input_number.echo_kuche_vol.state }}"

input_number:
  echo_kuche_vol:
    min: 0.0
    max: 1.0
    step: 0.1

