sensor:
  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Wirkenergie_Bezug_Summe_kWh"
    name: sml_output_wirkenergie_bezug_summe_kwh
    force_update: true
    unit_of_measurement: 'kWh'
    icon: mdi:flash
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Wirkenergie_Einspeisung_Summe_kWh"
    name: sml_output_wirkenergie_einspeisung_summe_kwh
    force_update: true
    unit_of_measurement: 'kWh'
    icon: mdi:flash
    device_class: power

  - platform: kostal_plenticore
    host: !secret wechselrichter_ip
    password: !secret wechselrichter_password
    monitored_conditions:
      - BatteryPercent
      - BatteryCycles
      - BatteryPower
      - HomeGridPower
      - HomeOwnPower
      - HomePVPower
      - HomeBatteryPower
      - GridPower
      - DCPower
      - PVPower
      - AutarkyDay
      - AutarkyMonth
      - AutarkyTotal
      - AutarkyYear
      - CO2SavingDay
      - CO2SavingMonth
      - CO2SavingTotal
      - CO2SavingYear
      - PV1Power
      - PV1Voltage
      - PV1Current
      - PV2Power
      - PV2Voltage
      - PV2Current
      - ACFrequency
      - ACL1Current
      - ACL1Power
      - ACL1Voltage
      - ACL2Current
      - ACL2Power
      - ACL2Voltage
      - ACL3Current
      - ACL3Power
      - ACL3Voltage
      - HomeConsumptionDay
      - HomeConsumptionMonth
      - HomeConsumptionTotal
      - HomeConsumptionYear
      - HomeConsumptionFromBatDay
      - HomeConsumptionFromBatMonth
      - HomeConsumptionFromBatTotal
      - HomeConsumptionFromBatYear
      - HomeConsumptionFromGridDay
      - HomeConsumptionFromGridMonth
      - HomeConsumptionFromGridTotal
      - HomeConsumptionFromGridYear
      - HomeConsumptionFromPVDay
      - HomeConsumptionFromPVMonth
      - HomeConsumptionFromPVTotal
      - HomeConsumptionFromPVYear
      - HomeConsumptionYieldDay
      - HomeConsumptionYieldMonth
      - HomeConsumptionYieldTotal
      - HomeConsumptionYieldYear