sensor:
  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Wirkenergie_Bezug_Summe_kWh"
    name: sml_output_wirkenergie_bezug_summe_kwh
    force_update: true
    unit_of_measurement: 'kWh'
    icon: mdi:flash
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Wirkenergie_Einspeisung_Summe_kWh"
    name: sml_output_wirkenergie_einspeisung_summe_kwh
    force_update: true
    unit_of_measurement: 'kWh'
    icon: mdi:flash
    device_class: power