sensor:
  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Wirkenergie_Bezug_Summe_Wh"
    name: sml_output_wirkenergie_bezug_summe_wh
    force_update: true
    unit_of_measurement: 'Wh'
    icon: mdi:power-socket-de
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Wirkenergie_Einspeisung_Summe_Wh"
    name: sml_output_wirkenergie_einspeisung_summe_wh
    force_update: true
    unit_of_measurement: 'Wh'
    icon: mdi:home-export-outline
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Momentanwirkleistung_Summe_W"
    name: sml_output_momentanwirkleistung_summe_w
    force_update: true
    unit_of_measurement: 'W'
    icon: mdi:flash
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Momentanwirkleistung_L1_W"
    name: sml_output_momentanwirkleistung_l1_w
    force_update: true
    unit_of_measurement: 'W'
    icon: mdi:flash
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Momentanwirkleistung_L2_W"
    name: sml_output_momentanwirkleistung_l2_w
    force_update: true
    unit_of_measurement: 'W'
    icon: mdi:flash
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Momentanwirkleistung_L3_W"
    name: sml_output_momentanwirkleistung_l3_w
    force_update: true
    unit_of_measurement: 'W'
    icon: mdi:flash
    device_class: power

  - platform: kostal_plenticore
    host: !secret wechselrichter_ip
    password: !secret wechselrichter_password
    monitored_conditions:
    #   - BatteryPercent
    #   - BatteryCycles
    #   - BatteryPower
    #   - HomeGridPower
    #   - HomeOwnPower
      - HomePVPower
    #   - HomeBatteryPower
      - GridPower
      - DCPower
      - PVPower
    #   - AutarkyDay
    #   - AutarkyMonth
    #   - AutarkyTotal
    #   - AutarkyYear
    #   - CO2SavingDay
    #   - CO2SavingMonth
    #   - CO2SavingTotal
    #   - CO2SavingYear
      - PV1Power
      - PV1Voltage
      - PV1Current
      - PV2Power
      - PV2Voltage
      - PV2Current
      - ACFrequency
      - ACL1Current
      - ACL1Power
      - ACL1Voltage
      - ACL2Current
      - ACL2Power
      - ACL2Voltage
      - ACL3Current
      - ACL3Power
      - ACL3Voltage
      - HomeConsumptionDay
      - HomeConsumptionMonth
      - HomeConsumptionTotal
      - HomeConsumptionYear
      - HomeConsumptionFromBatDay
      - HomeConsumptionFromBatMonth
      - HomeConsumptionFromBatTotal
      - HomeConsumptionFromBatYear
      - HomeConsumptionFromGridDay
      - HomeConsumptionFromGridMonth
      - HomeConsumptionFromGridTotal
      - HomeConsumptionFromGridYear
      - HomeConsumptionFromPVDay
      - HomeConsumptionFromPVMonth
      - HomeConsumptionFromPVTotal
      - HomeConsumptionFromPVYear
      - HomeConsumptionYieldDay
      - HomeConsumptionYieldMonth
      - HomeConsumptionYieldTotal
      - HomeConsumptionYieldYear

  - platform: template
    sensors:
      kostal_yield_day_kwh:
        friendly_name: "Stromerzeugung"
        unit_of_measurement: 'kWh'
        value_template: "{{ ((states('sensor.kostal_yield_day') | int) / 1000) | round(0) }}"
        icon_template: mdi:solar-power

      daily_ownconsumption_kwh:
        friendly_name: "Eigenverbrauch"
        unit_of_measurement: 'kWh'
        value_template: "{{ ((((states('sensor.kostal_yield_day') | int) | round(0)) - (states('sensor.daily_energy_einspeisung_wh') | int)) / 1000) }}"
        icon_template: mdi:home-import-outline
  
      daily_energy_bezug_kwh:
        friendly_name: "Netzbezug"
        unit_of_measurement: 'kWh'
        value_template: "{{ (((states('sensor.daily_energy_bezug_wh') | int) / 1000) | round(0)) }}"
        icon_template: mdi:power-socket-de

      daily_energy_einspeisung_kwh:
        friendly_name: "Einspeisung"
        unit_of_measurement: 'kWh'
        value_template: "{{ (((states('sensor.daily_energy_einspeisung_wh') | int) / 1000) | round(0)) }}"
        icon_template: mdi:home-export-outline
      

utility_meter:
  hourly_energy_bezug_wh:
    source: sensor.sml_output_wirkenergie_bezug_summe_wh
    cycle: hourly
  hourly_energy_einspeisung_wh:
    source: sensor.sml_output_wirkenergie_einspeisung_summe_wh
    cycle: hourly
  daily_energy_bezug_wh:
    source: sensor.sml_output_wirkenergie_bezug_summe_wh
    cycle: daily
  daily_energy_einspeisung_wh:
    source: sensor.sml_output_wirkenergie_einspeisung_summe_wh
    cycle: daily
  monthly_energy_bezug_wh:
    source: sensor.sml_output_wirkenergie_bezug_summe_wh
    cycle: monthly
  monthly_energy_einspeisung_wh:
    source: sensor.sml_output_wirkenergie_einspeisung_summe_wh
    cycle: monthly
  yearly_energy_bezug_wh:
    source: sensor.sml_output_wirkenergie_bezug_summe_wh
    cycle: yearly
  yearly_energy_einspeisung_wh:
    source: sensor.sml_output_wirkenergie_einspeisung_summe_wh
    cycle: yearly

