input_number:
  einspeiseverguetung:
    name: Einspeisevergütung [€/kWh]
    mode: box
    initial: 0.0917
    min: 0
    max: 1

  bezugskosten:
    name: Bezugskosten [€/kWh]
    mode: box
    initial: 0.2746
    min: 0
    max: 1
  
sensor:
  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Wirkenergie_Bezug_Summe_Wh"             
    name: sml_output_wirkenergie_bezug_summe_wh                           # Zählerstand Bezug in Wattstunden
    force_update: true
    unit_of_measurement: 'Wh'
    icon:  mdi:home-import-outline
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Wirkenergie_Einspeisung_Summe_Wh"
    name: sml_output_wirkenergie_einspeisung_summe_wh                     # Zählerstand Einspeisung in Wattstunden
    force_update: true
    unit_of_measurement: 'Wh'
    icon: mdi:home-export-outline
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Momentanwirkleistung_Summe_W"
    name: sml_output_momentanwirkleistung_summe_w                         # Zählerstand Momentanwirklestung in Watt
    force_update: true
    unit_of_measurement: 'W'
    icon: mdi:flash
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Momentanwirkleistung_L1_W"              
    name: sml_output_momentanwirkleistung_l1_w                            # Zählerstand Momentanwirklestung L1 in Watt
    force_update: true
    unit_of_measurement: 'W'
    icon: mdi:flash
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Momentanwirkleistung_L2_W"
    name: sml_output_momentanwirkleistung_l2_w                            # Zählerstand Momentanwirklestung L2 in Watt
    force_update: true
    unit_of_measurement: 'W'
    icon: mdi:flash
    device_class: power

  - platform: mqtt
    state_topic: "sml/ISKRA_MT175/Momentanwirkleistung_L3_W"
    name: sml_output_momentanwirkleistung_l3_w                            # Zählerstand Momentanwirklestung L3 in Watt
    force_update: true
    unit_of_measurement: 'W'
    icon: mdi:flash
    device_class: power

  - platform: kostal_plenticore
    host: !secret wechselrichter_ip
    password: !secret wechselrichter_password
    monitored_conditions:
      - BatteryPercent
      - BatteryCycles
      - BatteryPower
      - HomeGridPower
      - HomeOwnPower
      - HomePVPower
      - HomeBatteryPower
      - GridPower
      - DCPower
      - PVPower
      - AutarkyDay
      - AutarkyMonth
      - AutarkyTotal
      - AutarkyYear
      - CO2SavingDay
      - CO2SavingMonth
      - CO2SavingTotal
      - CO2SavingYear
      - PV1Power
      - PV1Voltage
      - PV1Current
      - PV2Power
      - PV2Voltage
      - PV2Current
      - ACFrequency
      - ACL1Current
      - ACL1Power
      - ACL1Voltage
      - ACL2Current
      - ACL2Power
      - ACL2Voltage
      - ACL3Current
      - ACL3Power
      - ACL3Voltage
      - HomeConsumptionDay
      - HomeConsumptionMonth
      - HomeConsumptionTotal
      - HomeConsumptionYear
      - HomeConsumptionFromBatDay
      - HomeConsumptionFromBatMonth
      - HomeConsumptionFromBatTotal
      - HomeConsumptionFromBatYear
      - HomeConsumptionFromGridDay
      - HomeConsumptionFromGridMonth
      - HomeConsumptionFromGridTotal
      - HomeConsumptionFromGridYear
      - HomeConsumptionFromPVDay
      - HomeConsumptionFromPVMonth
      - HomeConsumptionFromPVTotal
      - HomeConsumptionFromPVYear
      - HomeConsumptionYieldDay
      - HomeConsumptionYieldMonth
      - HomeConsumptionYieldTotal
      - HomeConsumptionYieldYear
      - OwnConsumptionRateDay
      - OwnConsumptionRateMonth
      - OwnConsumptionRateTotal
      - OwnConsumptionRateYear
      - MinSoC
      - SmartBatteryControl

  - platform: template
    sensors:
      feed_in_counter_kwh:
        friendly_name: "Zähler Einspeisung"
        unit_of_measurement: 'kWh'
        value_template: "{{ (((states('sensor.sml_output_wirkenergie_einspeisung_summe_wh') | float) / 1000) | round(0)) }}"
        icon_template: mdi:home-export-outline

      consumption_counter_kwh:
        friendly_name: "Zähler Bezug"
        unit_of_measurement: 'kWh'
        value_template: "{{ (((states('sensor.sml_output_wirkenergie_bezug_summe_wh') | float) / 1000) | round(0)) }}"
        icon_template: mdi:home-import-outline
  
      kostal_yield_day_rounded:
        friendly_name: "Stromerzeugung"
        unit_of_measurement: 'kWh'
        value_template: "{{ (states('sensor.kostal_yield_day') | int) | round(1) }}"
        icon_template: mdi:solar-power

      daily_ownconsumption_wh:
        friendly_name: "Eigenverbrauch"
        unit_of_measurement: 'Wh'
        value_template: "{{ ((states('sensor.kostal_yield_day') | int) * 1000) - (states('sensor.daily_energy_einspeisung_wh') | int) }}"
        icon_template: mdi:home-import-outline

      daily_ownconsumption_kwh:
        friendly_name: "Eigenverbrauch"
        unit_of_measurement: 'kWh'
        value_template: "{{ ((states('sensor.kostal_yield_day') | int) - (states('sensor.daily_energy_einspeisung_wh') | int)/ 1000)| round(0) }}"
        icon_template: mdi:home-import-outline
  
      daily_energy_bezug_kwh:
        friendly_name: "Netzbezug"
        unit_of_measurement: 'kWh'
        value_template: "{{ (((states('sensor.daily_energy_bezug_wh') | int) / 1000) | round(0)) }}"
        icon_template: mdi:power-socket-de

      daily_energy_einspeisung_kwh:
        friendly_name: "Einspeisung"
        unit_of_measurement: 'kWh'
        value_template: "{{ (((states('sensor.daily_energy_einspeisung_wh') | int) / 1000) | round(0)) }}"
        icon_template: mdi:home-export-outline
      
      actual_energy_production_w:
        friendly_name: Solarleistung
        unit_of_measurement: 'W'
        value_template: "{{ ((states('sensor.kostal_power_grid') | int) * (-1) ) }}"
        icon_template: mdi:solar-power
      
      actual_energy_consumption_w:
        friendly_name: Stromverbrauch
        unit_of_measurement: 'W'
        value_template: >
          {% if states('sensor.sml_output_momentanwirkleistung_summe_w_filtered') | int < 0 %}
              {{ (states('sensor.actual_energy_production_w_filtered')|int) + (states('sensor.sml_output_momentanwirkleistung_summe_w_filtered')|int) }}
            {% else %}
              {{ (states('sensor.sml_output_momentanwirkleistung_summe_w_filtered')|int) }}
          {% endif %}
        icon_template: mdi:home-import-outline

      actual_grid_consumption_w:
        friendly_name: Netzbezug
        unit_of_measurement: 'W'
        value_template: >
          {% if states('sensor.sml_output_momentanwirkleistung_summe_w_filtered') | int > 0 %}
              {{ (states('sensor.sml_output_momentanwirkleistung_summe_w_filtered')|int) }}
            {% else %}
              0
          {% endif %}
        icon_template: mdi:home-import-outline
          
      actual_grid_feed_in_w:
        friendly_name: Einspeisung
        unit_of_measurement: 'W'
        value_template: >
          {% if states('sensor.sml_output_momentanwirkleistung_summe_w_filtered') | int < 0 %}
              {{ (states('sensor.sml_output_momentanwirkleistung_summe_w_filtered')|int) * (-1) }}
            {% else %}
              0
          {% endif %}
        icon_template: mdi:home-import-outline

      actual_solar_consumption_w:
        friendly_name: Solarbezug
        unit_of_measurement: 'W'
        value_template: >
          {% if states('sensor.actual_energy_production_w_filtered') | int > 0 %}
              {{ (states('sensor.actual_energy_production_w_filtered') | int) - (states('sensor.actual_grid_feed_in_w') | int) }}
            {% else %}
              0
          {% endif %}
        icon_template: mdi:home-import-outline

      energy_cost_saving_today:
        friendly_name: Stromkostenersparnis (heute)
        unit_of_measurement: €
        value_template: >
          {{ (((((states('sensor.kostal_yield_day') | int) - (states('sensor.daily_energy_einspeisung_wh') | int)) / 1000) * (states('input_number.bezugskosten') | float)) * -1) | round(2) }}
        icon_template: mdi:currency-eur
      
      energy_compensation_today:
        friendly_name: Einspeisevergütung (heute)
        unit_of_measurement: €
        value_template: >
          {{ (((states('sensor.daily_energy_einspeisung_wh') | int) / 1000) * (states('input_number.einspeiseverguetung') | float)) | round(2) }}
        icon_template: mdi:currency-eur

      energy_costs_today:
        friendly_name: Stromkosten (heute)
        unit_of_measurement: €
        value_template: >
          {{ (((states('sensor.daily_energy_bezug_wh') | int) / 1000) * (states('input_number.bezugskosten') | float)) | round(2) }}
        icon_template: mdi:currency-eur

      energy_cost_balance_today:
        friendly_name: Stromkostenbilanz (heute)
        unit_of_measurement: €
        value_template: >
          {{ ((states('sensor.energy_costs_today') | float) - (states('sensor.energy_compensation_today') | float)) | round(2) }}
        icon_template: mdi:currency-eur
  

  - platform: filter
    name: 'sml_output_momentanwirkleistung_summe_w_filtered'
    entity_id: sensor.sml_output_momentanwirkleistung_summe_w
    filters:
      - filter: time_throttle
        window_size: 00:01:00
        precision: 0
  - platform: filter
    name: 'sml_output_momentanwirkleistung_l1_w_filtered'
    entity_id: sensor.sml_output_momentanwirkleistung_l1_w
    filters:
      - filter: time_throttle
        window_size: 00:01:00
        precision: 0
  - platform: filter
    name: 'sml_output_momentanwirkleistung_l2_w_filtered'
    entity_id: sensor.sml_output_momentanwirkleistung_l2_w
    filters:
      - filter: time_throttle
        window_size: 00:01:00
        precision: 0
  - platform: filter
    name: 'sml_output_momentanwirkleistung_l3_w_filtered'
    entity_id: sensor.sml_output_momentanwirkleistung_l3_w
    filters:
      - filter: time_throttle
        window_size: 00:01:00
        precision: 0
  - platform: filter
    name: 'actual_energy_production_w_filtered'
    entity_id: sensor.actual_energy_production_w
    filters:
      - filter: time_throttle
        window_size: 00:01:00
        precision: 0
  - platform: filter
    name: 'actual_energy_consumption_w_filtered'
    entity_id: sensor.actual_energy_consumption_w
    filters:
      - filter: time_throttle
        window_size: 00:01:00
        precision: 0
    
utility_meter:
  hourly_energy_bezug_wh:                                             # stündliche Bezugsmenge in Wattstunden
    source: sensor.sml_output_wirkenergie_bezug_summe_wh              
    cycle: hourly
  hourly_energy_einspeisung_wh:                                       # stündliche Einspeisung in Wattstunden
    source: sensor.sml_output_wirkenergie_einspeisung_summe_wh        
    cycle: hourly
  daily_energy_bezug_wh:                                              # tägliche Bezugsmenge in Wattstunden
    source: sensor.sml_output_wirkenergie_bezug_summe_wh  
    cycle: daily
  daily_energy_einspeisung_wh:                                        # tägliche Einspeisung in Wattstunden
    source: sensor.sml_output_wirkenergie_einspeisung_summe_wh
    cycle: daily
  monthly_energy_bezug_wh:                                            # monatliche Bezugsmenge in Wattstunden
    source: sensor.sml_output_wirkenergie_bezug_summe_wh
    cycle: monthly
  monthly_energy_einspeisung_wh:                                      # monatliche Einspeisung in Wattstunden
    source: sensor.sml_output_wirkenergie_einspeisung_summe_wh
    cycle: monthly
  yearly_energy_bezug_wh:                                             # jährliche Bezugsmenge in Wattstunden
    source: sensor.sml_output_wirkenergie_bezug_summe_wh
    cycle: yearly
  yearly_energy_einspeisung_wh:                                       # monatliche Einspeisung in Wattstunden
    source: sensor.sml_output_wirkenergie_einspeisung_summe_wh
    cycle: yearly

