#################################################################
#                                                               #
#                          Alexa Media                          #
#                                                               #
#################################################################

# alexa_media:
#   accounts:
#     - email: !secret alexa_user
#       password: !secret alexa_password
#       url: amazon.de
#       exclude_devices:
#         - "This Device"
#         - "Sandra's Alexa Apps"
#         - "Echo B"
#         - "Echo Offline"
#         - "Überall"
#         - "Marios 2. Fire"
#         - "Marios 3. Fire"
#         - "Mario's Fire TV stick Büro"
#         - "Mario's Fire TV stick"
#         - "Mario's Fire TV"
#"This Device","Sandra's Alexa Apps","Echo B","Echo Offline","Überall","Marios 2. Fire","Marios 3. Fire","Mario's Fire TV stick Büro","Mario's Fire TV stick","Mario's Fire TV"

media_player:

################# Soundtouch ####################################

  - platform: soundtouch
    host: !secret soundtouch_bad
    port: 8090
    name: Soundtouch Bad

  - platform: soundtouch
    host: !secret soundtouch_kueche
    port: 8090
    name: Soundtouch Küche

  - platform: androidtv
    name: Fire TV Cube
    host: !secret fire_tv_cube
    device_class: androidtv
    host: 192.168.0.222
    adbkey: "/config/android/adbkey"
    exclude_unnamed_apps: true
    apps:
      com.amazon.tv.launcher: "Fire TV"
      com.einsundeinstv.player:  "1&1 Fernsehen"
      Netflix: "Netflix"  
      com.amazon.firebat: "Amazon Prime"
      com.amazon.firetv.youtube: "YouTube"
      
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

      ####################################################
      #                                                  #
      #                CONDITIONAL MEDIA                 #
      #                                                  #
      ####################################################

input_select:
  conditional_media:
    initial: Spotify strehlma
    options:
      ['Zuletzt heruntergeladen', 'Spotify strehlma', 'Denon DNP-800NE', 'Soundtouch Küche', 'Soundtouch Bad']

automation:
  - alias: conditional_media_playing
    initial_state: true
    trigger:
      - platform: state
        entity_id: 
          ['media_player.spotify_strehlma', 'media_player.denon_dnp_800ne', 
          'media_player.soundtouch_kuche', 'media_player.soundtouch_bad']
        to: playing
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.conditional_media
          option: "{{ trigger.to_state.name }}"

  - alias: conditional_media_paused_idle
    initial_state: true
    trigger:
      - platform: state
        entity_id: 
          ['media_player.spotify_strehlma', 'media_player.denon_dnp_800ne', 
          'media_player.soundtouch_kuche', 'media_player.soundtouch_bad']
        to:
          ['off', 'idle', 'standby']
      - platform: state
        entity_id: 
          ['media_player.spotify_strehlma', 'media_player.denon_dnp_800ne', 
          'media_player.soundtouch_kuche', 'media_player.soundtouch_bad']
        to: paused
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.conditional_media
          option: >-
            {% set media_players = 
              [states.media_player.spotify_strehlma, states.media_player.denon_dnp_800ne, 
              states.media_player.soundtouch_kuche, states.media_player.soundtouch_bad] %}
            {% if media_players | selectattr('state','eq','playing') | list | count == 0 %}
              {% if media_players | selectattr('state','eq','paused') | list | count == 0 %}
              Zuletzt heruntergeladen
              {% else %}
              {{ media_players | selectattr('state','eq','paused') | map(attribute='name') | max }}
              {% endif %}
            {% else %}
            {{ media_players | selectattr('state','eq','playing') | map(attribute='name') | max }}
            {% endif %}
  - alias: conditional_media_all_off
    initial_state: true
    trigger:
      - platform: template
        value_template: >
          {{ is_state('media_player.spotify_strehlma', 'idle') and
          is_state('media_player.denon_dnp_800ne', 'idle') and
          is_state('media_player.soundtouch_kuche', 'standby') and
          is_state('media_player.soundtouch_bad', 'off') }}
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.conditional_media
          option: Zuletzt heruntergeladen
