switch:
  - platform: mqtt
    name: "shelf"
    state_topic: "home/433toMQTT"
    command_topic: "home/commands/MQTTto433/PLSL_180/433_1"
    payload_on: "4527377"
    payload_off: "4527380"
    optimistic: false
    qos: 0
    retain: true


# MQTT Payloads
#
# Livingroom remote:
#       ON          OFF
# A   4523345     4523348     Television    Moon
# B   4526417     4526420     Cube          Showcase
# C   4527185     4527188     Kitchenlight  Stairway
# D   4527377     4527380     Shelf 
#
# Kitchen remote:
#       ON          OFF
# A   279889      279892      Kitchenlight  Stairway
# B   282961      282964      Lightstrip    Xmas
# C   283729      283732
# D   283921      283924

automation:
  - alias: "MQTT Remote Television"
    initial_state: on
    trigger:
      - platform: mqtt
        topic: home/433toMQTT
        payload: '4523345' 
    action:
      service: switch.toggle
      entity_id: switch.tv_plug

  - alias: "MQTT Remote Moon"
    initial_state: on
    trigger:
      - platform: mqtt
        topic: home/433toMQTT
        payload: '4523348' 
    action:
      service: light.toggle
      entity_id: light.moon

  - alias: "MQTT Remote Cube"
    initial_state: on
    trigger:
      - platform: mqtt
        topic: home/433toMQTT
        payload: '4526417' 
    action:
      service: light.toggle
      entity_id: light.cube

  - alias: "MQTT Remote Showcase"
    initial_state: on
    trigger:
      - platform: mqtt
        topic: home/433toMQTT
        payload: '4526420' 
    action:
      service: switch.toggle
      entity_id: switch.showcase_plug

  # - alias: "MQTT Remote Shelf"
  #   initial_state: on
  #   trigger:
  #     - platform: mqtt
  #       topic: home/433toMQTT
  #       payload: '4527377' 
  #   action:
  #     service: switch.toggle
  #     entity_id: switch.shelf_plug

  - alias: "MQTT Remote Kitchenlight"
    initial_state: on
    trigger:
      - platform: mqtt
        topic: home/433toMQTT
        payload: '4527185' 
      - platform: mqtt
        topic: home/433toMQTT
        payload: '279889' 
    action:
      service: switch.toggle
      entity_id: switch.kitchen_plug

  - alias: "MQTT Remote Stairway"
    initial_state: on
    trigger:
      - platform: mqtt
        topic: home/433toMQTT
        payload: '4527188' 
      - platform: mqtt
        topic: home/433toMQTT
        payload: '279892' 
    action:
      service: switch.toggle
      entity_id: switch.stairway_plug

  - alias: "MQTT Remote Lightstripe"
    initial_state: on
    trigger:
      - platform: mqtt
        topic: home/433toMQTT
        payload: '282961' 
    action:
      service: switch.toggle
      entity_id: switch.lightstripe_plug

  - alias: "MQTT Remote XMAS"
    initial_state: on
    trigger:
      - platform: mqtt
        topic: home/433toMQTT
        payload: '282964' 
    action:
      service: switch.toggle
      entity_id: switch.xmas_plug
