input_boolean:
  nightstand_mario_manual:
  nightstand_sandra_manual:

input_number:
  nightstand_mario_brightness_trigger:
    name: Schaltschwelle
    unit_of_measurement: lux
    min: 0
    max: 10
    step: 0.2
  nightstand_mario_default_brightness:
    name: Helligkeit
    unit_of_measurement: lux
    min: 0
    max: 255
    step: 1
  nightstand_mario_light_duration:
    name: Schaltzeit
    unit_of_measurement: Sekunden
    min: 10
    max: 600
    step: 10
  nightstand_sandra_brightness_trigger:
    name: Schaltschwelle
    unit_of_measurement: lux
    min: 0
    max: 10
    step: 0.2
  nightstand_sandra_default_brightness:
    name: Helligkeit
    unit_of_measurement: lux
    min: 0
    max: 255
    step: 1
  nightstand_sandra_light_duration:
    name: Schaltzeit
    unit_of_measurement: Sekunden
    min: 10
    max: 600
    step: 10

input_text:
  nightstand_mario_default_rgb_color:
    name: Farbe
  nightstand_sandra_default_rgb_color:
    name: Farbe

light:
  - platform: template
    lights:
      - nightstand_mario_settings:
      - nightstand_mario_settings:

automation:
  - id: nightstand_mario_on
    alias: "Bewegung Nachttisch Mario"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.nightstand_mario_motion
        to: 'on'
    condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.nightstand_mario_motion
          state: 'on'
        - condition: template
          value_template: >
            {{ states('sensor.nightstand_mario_brightness')|float < states('input_number.nightstand_mario_brightness_trigger')|float }}
    action:
      service_template: >
        light.turn_on
      data:
        transition: 2
        # brightness: {{ states('input_number.nightstand_mario_default_brightness')|int }}
        # rgb_color: [255,0,0]
      entity_id: light.nightstand_mario_light

  - id: nightstand_mario_off
    alias: "Keine Bewegung Nachttisch Mario"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.nightstand_mario_motion
        to: 'off'
        for:
          seconds: "{{ states('input_number.nightstand_mario_light_duration')|int }}"  
    condition:
      - condition: state
        entity_id: input_boolean.nightstand_mario_manual
        state: 'off'
    action:
      service_template: >
        light.turn_off
      data:
        transition: 2
      entity_id: light.nightstand_mario_light

  - id: nightstand_sandra_on
    alias: "Bewegung Nachttisch Sandra"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.nightstand_sandra_motion
        to: 'on'
    condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.nightstand_sandra_motion
          state: 'on'
        - condition: template
          value_template: >
            {{ states('sensor.nightstand_sandra_brightness')|float < states('input_number.nightstand_sandra_brightness_trigger')|float }}
    action:
      service_template: >
        light.turn_on
      data:
        transition: 2
        # brightness: {{ states('input_number.nightstand_sandra_default_brightness')|int }}
        # rgb_color: [255,0,0]
      entity_id: light.nightstand_sandra_light

  - id: nightstand_sandra_off
    alias: "Keine Bewegung Nachttisch Sandra"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.nightstand_sandra_motion
        to: 'off'
        for:
          seconds: "{{ states('input_number.nightstand_sandra_light_duration')|int }}"  
    condition:
      - condition: state
        entity_id: input_boolean.nightstand_sandra_manual
        state: 'off'
    action:
      service_template: >
        light.turn_off
      data:
        transition: 2
      entity_id: light.nightstand_sandra_light

      # - service: light.turn_on
      #   data_template:
      #     entity_id: light.milight_gu10
      #     rgb_color:
      #       - '{{ states.sensor.random_rgb.state.split(",")[0] }}'
      #       - '{{ states.sensor.random_rgb.state.split(",")[1] }}'
      #       - '{{ states.sensor.random_rgb.state.split(",")[2] }}'
      #     brightness: 140