input_boolean:
  nightstand_mario_manual:
  nightstand_sandra_manual:

input_number:
  nightstand_mario_brightness_trigger:
    name: Schaltschwelle
    unit_of_measurement: lux
    min: 0
    max: 100
    step: 1
  nightstand_sandra_brightness_trigger:
    name: Schaltschwelle
    unit_of_measurement: lux
    min: 0
    max: 100
    step: 1

# light:
#   - platform: template
#     lights:
#       - nightstand_mario_light_settings
#   - platform: template
#     lights:
#       - nightstand_sandra_light_settings

automation:
  - alias: nightstand_mario_motion
    alias: "Bewegung Nachttisch Mario"
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.nightstand_mario_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.nightstand_mario_motion
      to: 'off'
      for:
        minutes: 5
  # condition:
  #   - condition: numeric_state
      #  entity_id: sensor.nightstand_mario_brightness
  #     below: 100
  action:
    service_template: >
      light.turn_{{ trigger.to_state.state}}
    # data_template:
    #   transition: 1
    entity_id: light.nightstand_mario_light
