input_boolean:
  nightstand_mario_manual:
    initial: off
  nightstand_sandra_manual:
    initial: off
  nightstand_mario_light_setting:
    initial: on
  nightstand_sandra_light_setting:
    initial: on
input_number:
  nightstand_mario_brightness_trigger:
    name: Schaltschwelle
    unit_of_measurement: lux
    min: 0
    max: 10
    step: 0.2
  nightstand_mario_default_brightness:
    name: Helligkeit
    unit_of_measurement: lux
    min: 0
    max: 255
    step: 1
  nightstand_mario_light_duration:
    name: Schaltzeit
    unit_of_measurement: Sekunden
    min: 10
    max: 600
    step: 10
  nightstand_mario_default_h:
    min: 0
    max: 360
  nightstand_mario_default_s:
    min: 0
    max: 360

  nightstand_sandra_brightness_trigger:
    name: Schaltschwelle
    unit_of_measurement: lux
    min: 0
    max: 10
    step: 0.2
  nightstand_sandra_default_brightness:
    name: Helligkeit
    unit_of_measurement: lux
    min: 0
    max: 255
    step: 1
  nightstand_sandra_light_duration:
    name: Schaltzeit
    unit_of_measurement: Sekunden
    min: 10
    max: 600
    step: 10
  nightstand_sandra_default_h:
    min: 0
    max: 360
  nightstand_sandra_default_s:
    min: 0
    max: 360

input_text:
  nightstand_mario_default_rgb_color:
    name: Farbe
  nightstand_sandra_default_rgb_color:
    name: Farbe

light:
  - platform: template
    lights:
      nightstand_mario_settings:
        turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.nightstand_mario_light_setting
        turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.nightstand_mario_light_setting
        color_template: "({{states('input_number.nightstand_mario_default_h') | float}}, {{states('input_number.nightstand_mario_default_s') | float}})"
        set_color:
          - service: input_number.set_value
            data_template:
              value: "{{ h }}"
              entity_id: input_number.nightstand_mario_default_h
          - service: input_number.set_value
            data_template:
              value: "{{ s }}"
              entity_id: input_number.nightstand_mario_default_s

      nightstand_sandra_settings:
        turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.nightstand_sandra_light_setting
        turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.nightstand_sandra_light_setting
        color_template: "({{states('input_number.nightstand_sandra_default_h') | float}}, {{states('input_number.nightstand_sandra_default_s') | float}})"
        set_color:
          - service: input_number.set_value
            data_template:
              value: "{{ h }}"
              entity_id: input_number.nightstand_sandra_default_h
          - service: input_number.set_value
            data_template:
              value: "{{ s }}"
              entity_id: input_number.nightstand_sandra_default_s





automation:
  - id: nightstand_mario_on
    alias: "Bewegung Nachttisch Mario"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.nightstand_mario_motion
        to: 'on'
    condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.nightstand_mario_motion
          state: 'on'
        - condition: template
          value_template: >
            {{ states('sensor.nightstand_mario_brightness')|float < states('input_number.nightstand_mario_brightness_trigger')|float }}
    action:
      service_template: >
        light.turn_on
      data:
        transition: 2
        # brightness: {{ states('input_number.nightstand_mario_default_brightness')|int }}
        # rgb_color: [255,0,0]
      entity_id: light.nightstand_mario_light

  - id: nightstand_mario_off
    alias: "Keine Bewegung Nachttisch Mario"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.nightstand_mario_motion
        to: 'off'
        for:
          seconds: "{{ states('input_number.nightstand_mario_light_duration')|int }}"  
    condition:
      - condition: state
        entity_id: input_boolean.nightstand_mario_manual
        state: 'off'
    action:
      service_template: >
        light.turn_off
      data:
        transition: 2
      entity_id: light.nightstand_mario_light

  - id: nightstand_sandra_on
    alias: "Bewegung Nachttisch Sandra"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.nightstand_sandra_motion
        to: 'on'
    condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.nightstand_sandra_motion
          state: 'on'
        - condition: template
          value_template: >
            {{ states('sensor.nightstand_sandra_brightness')|float < states('input_number.nightstand_sandra_brightness_trigger')|float }}
    action:
      # service_template: >
      #   light.turn_on
      # data:
      #   transition: 2
      #   # brightness: {{ states('input_number.nightstand_sandra_default_brightness')|int }}
      #   # rgb_color: [255,0,0]
      # entity_id: light.nightstand_sandra_light
      service: light.turn_on
      data_template:
        entity_id: light.nightstand_sandra_light
        hs_color:
          - "{{states('input_number.nightstand_sandra_default_h') | float}}"
          - "{{states('input_number.nightstand_sandra_default_s') | float}}"
        brightness: "{{states('input_number.nightstand_sandra_default_brightness') | int}}"


  - id: nightstand_sandra_off
    alias: "Keine Bewegung Nachttisch Sandra"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.nightstand_sandra_motion
        to: 'off'
        for:
          seconds: "{{ states('input_number.nightstand_sandra_light_duration')|int }}"  
    condition:
      - condition: state
        entity_id: input_boolean.nightstand_sandra_manual
        state: 'off'
    action:
      service_template: >
        light.turn_off
      data:
        transition: 2
      entity_id: light.nightstand_sandra_light

