input_boolean:
  nightstand_mario_manual:
  nightstand_sandra_manual:

input_number:
  nightstand_mario_brightness_trigger:
    name: Schaltschwelle
    unit_of_measurement: lux
    min: 0
    max: 100
    step: 1
  nightstand_mario_default_brightness:
    name: Helligkeit
    unit_of_measurement: lux
    min: 0
    max: 255
    step: 1
  nightstand_mario_light_duration:
    name: Schaltzeit
    unit_of_measurement: Sekunden
    min: 10
    max: 600
    step: 10
  nightstand_sandra_brightness_trigger:
    name: Schaltschwelle
    unit_of_measurement: lux
    min: 0
    max: 100
    step: 1
  nightstand_sandra_default_brightness:
    name: Helligkeit
    unit_of_measurement: lux
    min: 0
    max: 255
    step: 1
  nightstand_sandra_light_duration:
    name: Schaltzeit
    unit_of_measurement: Sekunden
    min: 10
    max: 600
    step: 10

input_text:
  nightstand_mario_default_rgb_color:
    name: Farbe
  nightstand_sandra_default_rgb_color:
    name: Farbe


automation:
  - id: nightstand_mario_motion
    alias: "Bewegung Nachttisch Mario"
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.nightstand_mario_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.nightstand_mario_motion
      to: 'off'
      for:
        seconds: "{{ states('input_number.nightstand_mario_light_duration')|int }}"  
    condition:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: binary_sensor.nightstand_mario_motion
            state: 'on'
          - condition: template
            value_template: >
              {{ states('sensor.nightstand_mario_brightness')|float < states('input_number.nightstand_mario_brightness_trigger')|float }}
        - condition: state
          entity_id: binary_sensor.nightstand_mario_motion
          state: 'off'
    action:
      service_template: >
        light.turn_{{ trigger.to_state.state}}
      data:
        transition: 2
        # brightness: "{{ states('input_number.nightstand_mario_default_brightness')|int }}"
        # rgb_color: [255,0,0]
      entity_id: light.nightstand_mario_light

  - id: nightstand_sandra_motion
    alias: "Bewegung Nachttisch Sandra"
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.nightstand_sandra_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.nightstand_sandra_motion
      to: 'off'
      for:
        seconds: "{{ states('input_number.nightstand_sandra_light_duration')|int }}"  
    condition:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: binary_sensor.nightstand_sandra_motion
            state: 'on'
          - condition: template
            value_template: >
              {{ states('sensor.nightstand_sandra_brightness')|float < states('input_number.nightstand_sandra_brightness_trigger')|float }}
        - condition: state
          entity_id: binary_sensor.nightstand_sandra_motion
          state: 'off'
    action:
      service_template: >
        light.turn_{{ trigger.to_state.state}}
      data:
        transition: 2
        # brightness: "{{ states('input_number.nightstand_sandra_default_brightness')|int }}"
        # rgb_color: [255,0,0]
      entity_id: light.nightstand_sandra_light

