#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.speedtest_ping:
      friendly_name: Ping
      icon: mdi:pulse
    sensor.speedtest_download:
      friendly_name: Download
      icon: mdi:arrow-down-bold
    sensor.speedtest_upload:
      friendly_name: Upload
      icon: mdi:arrow-up-bold


#################################################################
#                                                               #
#                          Speed Test                           #
#                                                               #
################################################################# 
  
speedtestdotnet:
  server_id: 17392
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
