tplink:
  discovery: false
  switch:
    - host: !secret tp_link_wellness
    - host: !secret tp_link_stairway
    - host: !secret tp_link_cube

automation:
  - alias: "Turn stairway on"
    hide_entity: true
    initial_state: on
    trigger:
      - platform: state
        entity_id: switch.stairway
        to: 'on'  
    action:
      service: homeassistant.turn_on
      entity_id: switch.stairway_plug
  
  - alias: "Turn stairway off"
    hide_entity: true
    initial_state: on
    trigger:
      - platform: state
        entity_id: switch.stairway
        to: 'off'  
    action:
      service: homeassistant.turn_off
      entity_id: switch.stairway_plug

