weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

sensor:
  - platform: darksky
    api_key: !secret darksky
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - summary
      - temperature
      - humidity
      - pressure
      - apparent_temperature
      - precip_probability
      - icon
      - precip_intensity
      - precip_accumulation
      - dew_point
      - wind_speed
      - wind_gust
      - wind_bearing
      - cloud_cover
      - visibility
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - moon_phase
      - sunrise_time
      - sunset_time
      - ozone
      - precip_type
    language: de

  - platform: buienradar
    name: 'buienradar'
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    timeframe: 120
    monitored_conditions:
      - stationname
      - barometerfc
      - barometerfcname
      - conditioncode
      - condition
      - conditiondetailed
      - conditionexact
      - conditionexact_1d
      - symbol
      - feeltemperature
      - temperature
      - groundtemperature
      - windspeed
      - windforce
      - windgust
      - rain_1d 
      - windspeed_1d 
      - rainchance_1d
      - precipitation
      - irradiance
      - precipitation_forecast_average
      - precipitation_forecast_total
      - rainlast24hour
      - rainlasthour